services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  drupal:
    image: drupal:10-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    restart: unless-stopped


volumes:
  db_data:
  drupal_data:
